#12.Highly Divisible Triangular Number
#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#Let us list the factors of the first seven triangle numbers:
#1: 1
#3: 1,3
#6: 1,2,3,6
#10: 1,2,5,10
#15: 1,3,5,15
#21: 1,3,7,21
#28: 1,2,4,7,14,28
#We can see that 28 is the first triangle number to have over five divisors.What is the value of the first triangle number to have over five hundred divisors?

import math

def triangular_nos(num):
    s = 0
    numbers = []
    for i in range(1, num + 1):
        s += i
        numbers.append(s)
    return numbers

def count_divisors(triangular_num):
    divisors = 0
    i = 1
    while i * i <= triangular_num:
        if triangular_num % i == 0:
            if i * i == triangular_num:
                divisors += 1
            else:
                divisors += 2
        i += 1
    return divisors

def find_triangle_number(target_divisors):
    triangle_number = 1
    current= 1

    while True:
        if current % 2 == 0:
            triangle_number = (current // 2) * (current + 1)
        else:
            triangle_number = current * ((current + 1) // 2)

        divisors = count_divisors(triangle_number)

        if divisors > target_divisors:
            return triangle_number

        current += 1

result = find_triangle_number(500)
print(result)

#output:76576500
